items:
  gold_rank:
    slot: 0
    item: GOLD_BLOCK
    name: "&e&lGOLD RANG"
    lore:
      - "§cDieser Kostet 101010$"
  fly_permission:
    slot: 1
    item: GREEN_DYE
    name: "&7/fly"
    lore:
      - "§cDamit kannst du Fliegen."