name: SlowRights
version: '1.2'
main: plugin.slowRights.SlowRights
api-version: '1.21'
authors: [ Jxst_Kirito ]
commands:
  rechte:
    description: Zeigt die Rechte des Spielers an
    usage: /rechte

permissions:
  slowrights.rechte:
    description: Erlaubt es dem Spieler, seine Rechte anzuzeigen
    default: true
